name: traefik

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: always
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api=${TRAEFIK_DASHBOARD_ENABLE:-false}"
    env_file:
      - .env
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
      - ./dashboard_users:/etc/traefik/dashboard_users:ro
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD_ENABLE:-false}"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik.example.com}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/dashboard_users"
      # Redirect HTTP to HTTPS for dashboard
      - "traefik.http.routers.dashboard_http.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik.example.com}`)"
      - "traefik.http.routers.dashboard_http.entrypoints=web"
      - "traefik.http.routers.dashboard_http.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    networks:
      - web

networks:
  web:
    external: true
    name: web
