# Global Traefik configuration for multi-app hosting

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      # Email is configured via environment variable mapping in docker-compose.yml
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

http:
  middlewares:
    security-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        # Headers for WebSocket and SSE support
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"

serversTransport:
  forwardingTimeouts:
    dialTimeout: "30s"
    responseHeaderTimeout: "0s"
    idleConnTimeout: "90s"
